### ISSUE TITLE
How can I receive the data for the code？

### ISSUE THREAD

**Issue by ymmmmmy** [shubhadityaburela/DL-ROM#2]
Here there, i know you are busy for your projects so you don't have time to manage this repo, or you may forget upload the useful data for this repo, so could you please upload a revelant data for this repo. That's import for me! Thank you very much !

**Comment by shubhadityaburela** [comment]
Hi, I have added a file `main.py `. It contains a very simple example of polynomial prediction. Just have a look. It has plot functions as well so that you can visualise the data and the prediction as well. You might need to tune the network itself for better prediction accuracies. This example is there just to give an idea of how the input and the parameters might look like. The library itself can be moulded to one's own needs be it image recognition or other stuff. 

Anyways If you have questions regarding the file or input data just write here.
